spring:
  datasource:
    url: jdbc:mysql://localhost:3306/development?useSSL=false&serverTimezone=UTC
    username: dev
    password: password2023
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
